version: '3'
services:
  postgres:
    container_name: postgres
    image: postgres:12.3
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=ucord_db
    networks:
      - ucord-service-net

  redis:
    image: redis:7.0.12
    ports:
      - "5444:6379"
    networks:
      - ucord-service-net


    #Если во фронте - закоментить build: и поднастройки, разкоментить image:
    #Сбилдить образ: docker build -t shykamuy/ucord_auth_service .
    #Пушнуть: docker push shykamuy/ucord_auth_service

  ucord_auth_service:
#    build:
#      context: ..\ucord_auth_service
#      dockerfile: ..\ucord_auth_service\Dockerfile
    image: shykamuy/ucord_auth_service:latest
    container_name: app
    depends_on:
      - redis
      - postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/ucord_db
      - SPRING_DATA_REDIS_HOST=redis
      - SPRING_DATA_REDIS_PORT=6379
      - APP_JWT_SECRET=someSecretKey
      - APP_JWT_TOKEN_EXPIRATION=30m
      - APP_JWT_REFRESH_TOKEN_EXPIRATION=1d
    ports:
      - "8080:8080"
    networks:
      - ucord-service-net
    restart: on-failure

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - ucord_auth_service
    networks:
      - ucord-service-net




networks:
  ucord-service-net: