version: '3'
services:
  postgres:
    container_name: postgres
    image: postgres:12.3
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=ucord_db
    networks:
      - ucord-service-net

  redis:
    image: redis:7.0.12
    ports:
      - "6379:6379"
    networks:
      - ucord-service-net

  ucord_service:
    build:
      context: ..\ucord_service
      dockerfile: ..\ucord_service\Dockerfile
    container_name: app
    depends_on:
      - redis
      - postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/ucord_db
      - SPRING_DATA_REDIS_HOST=redis
      - SPRING_DATA_REDIS_PORT=6379
      - APP_JWT_SECRET=someSecretKey
      - APP_JWT_TOKEN_EXPIRATION=3m
      - APP_JWT_REFRESH_TOKEN_EXPIRATION=30m
    ports:
      - "8080:8080"
    networks:
      - ucord-service-net
    restart: on-failure

networks:
  ucord-service-net:
